### ISSUE TITLE
Test views on 18 (John)

### ISSUE THREAD

**Issue by aquaaerobicsystem** [aquaaerobicsystem/aqua57Migration#17]

**Comment by aquaaerobicsystem** [comment]
@JSummersAqua , are your views working on Aqua18? @ckonkolaqua

**Comment by JSummersAqua** [comment]
I only have the one that I know about and it is working.

**Comment by ckonkolaqua** [comment]
Ok

**Comment by JSummersAqua** [comment]
The name is AerationandMixingShipScheduleTEST
