### ISSUE TITLE
Send chuck email on what View on 18 to move to 26 (John)

### ISSUE THREAD

**Issue by aquaaerobicsystem** [aquaaerobicsystem/aqua57Migration#18]

**Comment by aquaaerobicsystem** [comment]
@JSummersAqua did you just change the name of view on Aqua26? If so, please confirm and close. Thanks, @ckonkolaqua

**Comment by JSummersAqua** [comment]
Yes I did. Issue can be closed.

![image](https://user-images.githubusercontent.com/39597717/140540795-5d7c5777-6f54-4a6b-878f-c2f79b898030.png)
