### ISSUE TITLE
* John & Paul dev DB's in maintenance mode before and after

### ISSUE THREAD

**Issue by aquaaerobicsystem** [aquaaerobicsystem/aqua57Migration#9]

**Comment by aquaaerobicsystem** [comment]
This is completed

**Comment by aquaaerobicsystem** [comment]
@JSummersAqua @phstanek Did you take DEV out of maintenance mode?

**Comment by phstanek** [comment]
@aquaaerobicsystem 
We literally just verified the nightly refresh worked 2 minutes ago.  DEV systems will be taken out of maintenance mode in the next few minutes.

**Comment by phstanek** [comment]
@aquaaerobicsystem RP Dev and APD Dev systems have been taken out of maintenance mode.

**Comment by ckonkolaqua** [comment]
Great! Thanks Paul!
